# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startMenu3.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1016, 755)
        MainWindow.setMinimumSize(QtCore.QSize(1016, 755))
        MainWindow.setMaximumSize(QtCore.QSize(1016, 755))
        MainWindow.setStyleSheet("QWidget#centralwidget {\n"
"    background-image: url(C:/git/fcdb/Football-Club-DB/fcdb/back22.jpg);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.enterButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.enterButton.setGeometry(QtCore.QRect(375, 535, 281, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.enterButton.setFont(font)
        self.enterButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.enterButton.setStyleSheet(" color: rgb(255, 129, 129)")
        icon = QtGui.QIcon.fromTheme("NO")
        self.enterButton.setIcon(icon)
        self.enterButton.setIconSize(QtCore.QSize(300, 300))
        self.enterButton.setObjectName("enterButton")
        self.siteLabel = QtWidgets.QLabel(self.centralwidget)
        self.siteLabel.setGeometry(QtCore.QRect(610, 660, 437, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.siteLabel.setFont(font)
        self.siteLabel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.siteLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.siteLabel.setOpenExternalLinks(True)
        self.siteLabel.setObjectName("siteLabel")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 971, 171))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(25)
        self.label_3.setFont(font)
        self.label_3.setAcceptDrops(False)
        self.label_3.setStyleSheet("color: rgb(244, 236, 233);\n"
"border-color: rgb(0, 0, 0);")
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.noAccountButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.noAccountButton.setGeometry(QtCore.QRect(0, 650, 281, 48))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.noAccountButton.setFont(font)
        self.noAccountButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.noAccountButton.setStyleSheet("color: rgb(255, 255, 255);")
        icon = QtGui.QIcon.fromTheme("NO")
        self.noAccountButton.setIcon(icon)
        self.noAccountButton.setObjectName("noAccountButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1016, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.enterButton.setText(_translate("MainWindow", "ВОЙТИ"))
        self.siteLabel.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"https://www.manutd.com/\"><span style=\" text-decoration: underline; color:#aaffff;\">Official Manchester United Website</span></a></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "ДОБРО ПОЖАЛОВАТЬ В БАЗУ ДАННЫХ ФУТБОЛЬНОЙ КОМАНДЫ"))
        self.noAccountButton.setText(_translate("MainWindow", "У меня нет аккаунта"))
